# SAIBA - Vi omsætter ny teknologi til værdi for jeres virksomhed
# Jekyll Configuration for GitHub Pages

# Site settings
title: "SAIBA"
tagline: "Vi omsætter ny teknologi til værdi for jeres virksomhed"
description: "Fra hverdagens rutiner til ekstraordinære superkræfter med AI for dine medarbejdere"
baseurl: "/saibaweb"
url: "https://b4ltasar.github.io"
repository: "b4ltasar/saibaweb"

# Build settings
markdown: kramdown
highlighter: rouge
theme: minima

# Collections
collections:
  services:
    output: true
    permalink: /:name/
  team:
    output: true
    permalink: /team/:name/
  clients:
    output: true
    permalink: /clients/:name/

# Defaults
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "services"
    values:
      layout: "service"
  - scope:
      path: ""
      type: "team"
    values:
      layout: "team-member"
  - scope:
      path: ""
      type: "clients"
    values:
      layout: "client"

# Plugins for GitHub Pages
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md
  - package.json
  - package-lock.json
  - .sass-cache/
  - .jekyll-cache/
  - .jekyll-metadata
  - .git
  - .gitignore
  - .vscode

# Include files
include:
  - _redirects

# SEO
author: "SAIBA"
social:
  name: "SAIBA"
  links:
    - "https://linkedin.com/company/saiba"

# Custom variables
lang: "da"
timezone: "Europe/Copenhagen"

